export enum ExceptionCodes {
  GENERIC_INTERNAL = 'IER001',
  USER_ALREADY_REGISTERED = 'USER002',
  USER_SECRET_NOT_FOUND = 'USER003',
  USER_NOT_ALLOWED = 'USER005',
  USER_NOT_ACTIVE = 'USER006',
  USER_NOT_FOUND = 'USER007',
  USER_NOT_AUTHORIZED = 'USER005',
  USER_FORBIDDEN = 'USER009',

  ROLE_ALREADY_REGISTERED = 'ROLE002',
  ROLE_NOT_FOUND = 'ROLE007',

  COUNTRY_ALREADY_REGISTERED = 'COUNTRY002',
  COUNTRY_NOT_FOUND = 'COUNTRY007',

  ZONE_ALREADY_REGISTERED = 'ZONE002',
  ZONE_NOT_FOUND = 'ZONE007',

  DISTRICT_ALREADY_REGISTERED = 'DISTRICT002',
  DISTRICT_NOT_FOUND = 'DISTRICT007',

  STATE_ALREADY_REGISTERED = 'STATE002',
  STATE_NOT_FOUND = 'STATE007',

  CITY_ALREADY_REGISTERED = 'CITY002',
  CITY_NOT_FOUND = 'CITY007',

  NOTIFICATION_TYPE_ALREADY_REGISTERED = 'NOTIFICATION_TYPE002',
  NOTIFICATION_TYPE_NOT_FOUND = 'NOTIFICATION_TYPE007',

  AUTHORIZATION_HEADER_NOT_FOUND = 'AUTH001',

  ENVIRONMENT_VARIABLE_NOT_FOUND = 'ENVVARNOTFOUND',

  MISSING_FILED_OR_INVALID_TYPE = 'VALIDATION001',
  INVALID_JWT_TOKEN = 'AUTH002',

  CUSTOM_HTTP_EXCEPTION = 'CUSTOM_HTTP_EXCEPTION',
}
