name: API-CI-CD
# TRIGER/EVENTO QUE DISPARA A AUTOMAÇÃO
# on: ele é o cara que fica escutando o evento definido, que nesse caso é o push na branch main
on: 
  push:
    branches: ["master"]
  workflow_dispatch:
# definie minhas tarefas
# job: conjunto de tarefas
jobs:
# definindo a job(ci) preciso informar o run( que tarefa ele era fazer )
# runs-on: defino onde vou executar minha automação
# steps: seria os passos/sequencia de execução
  ci:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: 0.10.3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./docker/pipeline.dockerfile
          tags: | 
            robyrt/api-catalago:latest
            robyrt/api-catalago:${{ github.run_number }}